<?php

declare(strict_types=1);

namespace Lattice\Ui\Enums;

// Generated by @lattice-php/vite-svg-sprite. Do not edit.
enum Icon: string
{
    case AlignCenter = 'align-center';
    case AlignJustify = 'align-justify';
    case AlignLeft = 'align-left';
    case AlignRight = 'align-right';
    case ArrowDown = 'arrow-down';
    case ArrowLeftToLine = 'arrow-left-to-line';
    case ArrowRightToLine = 'arrow-right-to-line';
    case ArrowUp = 'arrow-up';
    case Bell = 'bell';
    case Bold = 'bold';
    case Calendar = 'calendar';
    case Check = 'check';
    case ChevronDown = 'chevron-down';
    case ChevronLeft = 'chevron-left';
    case ChevronRight = 'chevron-right';
    case ChevronsUpDown = 'chevrons-up-down';
    case CircleAlert = 'circle-alert';
    case CircleCheck = 'circle-check';
    case CircleHelp = 'circle-help';
    case CircleX = 'circle-x';
    case Clock = 'clock';
    case Code = 'code';
    case CodeXml = 'code-xml';
    case Columns2 = 'columns-2';
    case Columns3 = 'columns-3';
    case Copy = 'copy';
    case CornerDownRight = 'corner-down-right';
    case ExternalLink = 'external-link';
    case Eye = 'eye';
    case EyeOff = 'eye-off';
    case Filter = 'filter';
    case GripVertical = 'grip-vertical';
    case Heading = 'heading';
    case Heading1 = 'heading-1';
    case Heading2 = 'heading-2';
    case Heading3 = 'heading-3';
    case Heading4 = 'heading-4';
    case Heading5 = 'heading-5';
    case Heading6 = 'heading-6';
    case Highlighter = 'highlighter';
    case Image = 'image';
    case Images = 'images';
    case Info = 'info';
    case Italic = 'italic';
    case LayoutDashboard = 'layout-dashboard';
    case LayoutTemplate = 'layout-template';
    case Link = 'link';
    case List = 'list';
    case ListOrdered = 'list-ordered';
    case ListPlus = 'list-plus';
    case Loader2 = 'loader-2';
    case Minus = 'minus';
    case MoreHorizontal = 'more-horizontal';
    case MoveVertical = 'move-vertical';
    case PanelLeft = 'panel-left';
    case Pencil = 'pencil';
    case PencilLine = 'pencil-line';
    case Pilcrow = 'pilcrow';
    case Plus = 'plus';
    case Quote = 'quote';
    case Redo2 = 'redo-2';
    case RotateCcw = 'rotate-ccw';
    case Rows3 = 'rows-3';
    case Search = 'search';
    case Send = 'send';
    case Settings = 'settings';
    case Smile = 'smile';
    case Square = 'square';
    case Strikethrough = 'strikethrough';
    case Table = 'table';
    case Trash2 = 'trash-2';
    case Underline = 'underline';
    case Undo2 = 'undo-2';
    case X = 'x';
}
